logging:
    level:
        org:
            hibernate:
                SQL: debug
security:
    jwt:
        secret-key: xghJdkL55gshSjK76sfhFDlQfalSfldjkShgf56748gDkdFgChjll
spring:
    application:
        name: NewTopSquadProject
    datasource:
        password: password
        url: jdbc:mysql://localhost:3306/TopSquad
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
